- alias: 'RGB Alarm Clock'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_clock_time_long.state }}'
  condition:
    condition: state
    entity_id: input_boolean.alarm_clock_status
    state: 'on'
  action:
    service: script.wake_up

- alias: 'Bed Light Trigger'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      unique_id: '00:12:4b:00:1c:d6:0e:fb'
  action:
    - service: light.toggle
      data:
        entity_id: light.bed_led_strip

- alias: 'Volumio Play Pause'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      unique_id: '00:12:4b:00:1c:d6:0d:9d'
  action:
    - service: media_player.media_play_pause
      data:
        entity_id: media_player.volumio

