# removed default config, re-add stuff here
automation: !include_dir_merge_list automation/
config:
counter:
frontend:
  themes: !include themes.yaml
group: !include groups.yaml
history:
http:
  use_x_forwarded_for: true
  trusted_proxies: 3.125.2.80
image:
input_boolean: !include input/boolean.yaml
input_datetime:
input_number: !include input/number.yaml
input_select:
input_text:
light: !include light.yaml
logbook:
homeassistant:
  customize: !include customize.yaml
map:
media_source:
mobile_app:
mqtt: !include mqtt.yaml
person:
scene:
script: !include scripts.yaml
sensor: !include sensor.yaml
ssdp:
sun:
switch: !include switch.yaml
system_health:
tag:
timer:
webhook:
zeroconf:
zone:
