
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

input_number: !include input/number.yaml
input_boolean: !include input/boolean.yaml

sensor: !include sensor.yaml

switch: !include switch.yaml

light: !include light.yaml

mqtt: !include mqtt.yaml

homeassistant:
  customize: !include customize.yaml
  
