- platform: mqtt
  name: "Living Room Light"
  state_topic: "shellies/shelly1-767C05/relay/0"
  command_topic: "shellies/shelly1-767C05/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
